### PR TITLE
Changing the subtitles on Section 24 Storing User Passwords at 03:12

### PR DESCRIPTION
**Pull request by AncaWebDev**
Changing from 
"03:12.260 --> 03:20.510
va deveni jalnic și nimeni în mijloc nu va putea vedea acest lucru sau o vor putea vedea, dar nu"

To 
"03:12.260 --> 03:20.510
va deveni criptata și nimeni în mijloc nu o va putea vedea sau o vor putea vedea, dar "

### CODE REVIEW

**Comment by MattCSmith** [comment]
@AncaWebDev ,
Thank you for the Pull Request, I have tagged and notified @aneagoie so that he may check and merge this  and apply it to the course.

Regards
Matt

**Comment by AncaWebDev** [comment]
the words in English were "jumbled up " :)

**Review by aneagoie — CHANGES_REQUESTED** [review]
This looks great! Thanks for doing this @AncaWebDev . Just a quick fix... looks like you added the .DS_Store files in the PR. Could you remove those? After that I can merge the changes!

**Comment by AncaWebDev** [comment]
Done !

**Comment by aneagoie** [comment]
hmm, I still see them there 😄 . Might be the easies to just create a new PR?

**Comment by MattCSmith** [comment]
Closing as no longer needed

**Pull request closed without merging**
